[package]
name = "backend_api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
redis = "0.26.0"
sqlx = { version = "0.8.0", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1.39.1", features = ["full"] }
