[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
redis = "0.23.3"
sqlx = { version = "0.7.2", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1.33.0", features = ["full"] }
